# Flair Embeddings Basics

## Flair Embeddings Tutorial

https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_3_WORD_EMBEDDING.md

## Was sind Word Embeddings?

### Video

Information Service Engineering 2021,
Prof. Dr. Harald Sack,
Karlsruhe Institute of Technology

https://www.youtube.com/watch?v=EG4x0SKb4h0&list=PLNXdQl4kBgzsi4WsCeCKOGSQdH-gWgt7R&index=6

https://www.youtube.com/watch?v=LSMtLYWAfw0&list=PLNXdQl4kBgztwKrKv69LPAqqX1vgHENSi&index=6


## >>> gute Visualisierung in Büchern suchen

## Imports

In [1]:
from flair.embeddings import WordEmbeddings, FlairEmbeddings, StackedEmbeddings
from flair.data import Sentence

In [46]:
text = '''Biden befürchtet Einmarsch "in den nächsten Tagen"
            Stand: 18.02.2022 06:01 Uhr
            Die Gefahr eines russischen Einmarsches in die Ukraine schätzt US-Präsident Biden als "sehr hoch" ein - schon in den kommenden Tagen könne es dazu kommen. Die russische Regierung wies den Vize-US-Botschafter in Moskau aus.
            US-Präsident Joe Biden befürchtet trotz aller Beteuerungen aus Moskau einen russischen Einmarsch in die Ukraine in den kommenden Tagen. Biden sagte, die Gefahr einer Invasion sei "sehr hoch". Nach seiner Einschätzung könne es "in den nächsten paar Tagen" dazu kommen. Es gebe keine Pläne dafür, dass er mit dem russischen Präsidenten Wladimir Putin telefonieren werde, fügte er hinzu.
            Der Kreml erklärte laut der russischen Agentur RIA, Bidens Warnung verstärke die Spannungen noch. Der stellvertretende Außenminister Sergej Werschinin wies vor dem UN-Sicherheitsrat die Befürchtungen des Westens vor einem bevorstehenden Einmarsch erneut zurück. "Ich denke, wir haben genug darüber spekuliert", sagte er. Eine Invasion sei entgegen der Warnungen ausgeblieben. In Richtung der USA und ihrer westlichen Verbündeten sagte Werschinin: "Mein Rat an Sie ist, sich nicht in eine unangenehme Situation zu begeben."
            Biden will am heutigen Freitag mit Verbündeten über das weitere Vorgehen beraten. Themen der Telefonschalte am Nachmittag (Ortszeit) sollten unter anderem die Aufstockung der russischen Truppen an der Grenze zur Ukraine und weitere diplomatische Bemühungen sein, hieß es aus dem Weißen Haus. Neben Kanadas Premierminister Justin Trudeau sollen führende Politiker aus Deutschland, Frankreich, Großbritannien, Italien, Polen und Rumänien an dem Gespräch teilnehmen, teilte Trudeaus Büro am Donnerstagabend (Ortszeit) mit. Auch die Europäische Union und die NATO seien vertreten.
            US-Außenminister Antony Blinken will sich nächste Woche mit seinem russischen Kollegen Sergej Lawrow treffen - solange Russland nicht in der Ukraine einmarschiert. Blinken habe vorgeschlagen, sich mit Lawrow "nächste Woche in Europa zu treffen. Die Russen haben mit Terminvorschlägen für Ende nächster Woche geantwortet, was wir unter der Bedingung akzeptiert haben, dass es keine russische Invasion der Ukraine gibt", erklärte der Sprecher des Außenministeriums, Ned Price, am Abend.
            Zuvor hatte Blinken vor dem UN-Sicherheitsrat ebenfalls gewarnt, Russland bereite sich auf einen Angriff in den kommenden Tagen vor. Russlands Plan sei, dafür einen Vorwand zu schaffen. "Dies könnte ein gewaltsames Ereignis sein, das Russland gegen die Ukraine vorbringen wird, oder eine unerhörte Anschuldigung, die Russland gegen die ukrainische Regierung erheben wird", sagte er. Möglich wären ihm zufolge ein vermeintlicher Terroranschlag in Russland, die "erfundene Entdeckung eines Massengrabes" und Vorwürfe eines Völkermordes, ein inszenierter Drohnenangriff auf Zivilisten oder ein vorgetäuschter oder echter Angriff mit Chemiewaffen.
            Russische Medien würden bereits "falsche Alarme" verbreiten, so Blinken. Ein russischer Angriff könne auch die ukrainische Hauptstadt Kiew einbeziehen. Der US-Außenminister betonte, Diplomatie sei weiter der wichtigste Weg zur Lösung der Krise. Er habe daher seinem russischen Amtskollegen Sergej Lawrow ein persönliches Treffen in der kommenden Woche vorgeschlagen. 
            '''

## Word Embeddings

Liste der klassichen Word Embeddings:

https://github.com/flairNLP/flair/blob/master/resources/docs/embeddings/CLASSIC_WORD_EMBEDDINGS.md

In [47]:
embedding = WordEmbeddings('de')

In [48]:
%%time

# Erstellen des Sentence-Objekts
text = Sentence(text)

Wall time: 21.2 ms


In [49]:
%%time

# Erstellen der Word Embeddings
embedding.embed(text)

Wall time: 31.6 ms


[Sentence: "Biden befürchtet Einmarsch " in den nächsten Tagen " Stand : 18.02.2022 06:01 Uhr Die Gefahr eines russischen Einmarsches in die Ukraine schätzt US-Präsident Biden als " sehr hoch " ein - schon in den kommenden Tagen könne es dazu kommen . Die russische Regierung wies den Vize-US-Botschafter in Moskau aus . US-Präsident Joe Biden befürchtet trotz aller Beteuerungen aus Moskau einen russischen Einmarsch in die Ukraine in den kommenden Tagen . Biden sagte , die Gefahr einer Invasion sei " sehr hoch " . Nach seiner Einschätzung könne es " in den nächsten paar Tagen " dazu kommen . Es gebe keine Pläne dafür , dass er mit dem russischen Präsidenten Wladimir Putin telefonieren werde , fügte er hinzu . Der Kreml erklärte laut der russischen Agentur RIA , Bidens Warnung verstärke die Spannungen noch . Der stellvertretende Außenminister Sergej Werschinin wies vor dem UN-Sicherheitsrat die Befürchtungen des Westens vor einem bevorstehenden Einmarsch erneut zurück . " Ich denke , wir 

In [53]:
for token in text[:5]:
    print(token)
    print(token.embedding)

Token: 1 Biden
tensor([-7.8923e-02,  2.4628e-01, -3.8108e-01, -6.2871e-01,  3.8367e-01,
         5.3533e-01,  2.8005e-02,  4.0969e-01,  2.8747e-01,  4.1506e-01,
         8.4334e-03, -6.4162e-03,  3.5484e-01, -2.1080e-01, -1.5462e-01,
        -4.5055e-01, -2.4137e-01,  1.0655e-01, -9.0998e-01,  2.1993e-01,
         1.2067e-01, -2.4979e-01, -7.2511e-02, -8.5835e-02, -1.9839e-01,
        -1.3344e-01, -5.7131e-01, -1.8463e-01, -3.1098e-01, -4.1582e-01,
         1.7205e-01,  2.8265e-02, -4.4262e-01,  7.4274e-03,  8.6720e-02,
        -2.7014e-01,  3.1015e-01, -5.3546e-01, -4.1678e-01, -1.2758e-01,
        -2.3226e-01, -3.6083e-01,  5.9496e-02, -7.8684e-03, -1.2107e-01,
        -1.7956e-01, -5.6662e-01, -4.5334e-02,  2.5439e-02, -2.0734e-01,
         5.1500e-02,  2.9675e-01, -1.5524e-01, -1.4948e-02, -3.4001e-02,
        -2.3703e-01,  3.1869e-01, -2.3203e-01,  1.2610e-01,  3.2230e-01,
        -4.8734e-02, -1.4125e-01,  4.3318e-01,  3.4058e-01, -6.4771e-01,
         1.1643e-01, -2.7466e-01,  4

## Flair Embeddings

Liste von vortrainierten Flair Embeddings:

https://github.com/flairNLP/flair/blob/master/resources/docs/embeddings/FLAIR_EMBEDDINGS.md

In [10]:
flair_embedding_forward = FlairEmbeddings('de-forward')
flair_embedding_backward = FlairEmbeddings('de-backward')

2022-02-24 16:33:38,217 https://flair.informatik.hu-berlin.de/resources/embeddings/flair/lm-mix-german-forward-v0.2rc.pt not found in cache, downloading to C:\Users\nitra\AppData\Local\Temp\tmpafgfgstv


100%|██████████| 72818995/72818995 [00:12<00:00, 5666109.16B/s]

2022-02-24 16:33:51,218 copying C:\Users\nitra\AppData\Local\Temp\tmpafgfgstv to cache at C:\Users\nitra\.flair\embeddings\lm-mix-german-forward-v0.2rc.pt


2022-02-24 16:33:51,264 removing temp file C:\Users\nitra\AppData\Local\Temp\tmpafgfgstv
2022-02-24 16:33:51,616 https://flair.informatik.hu-berlin.de/resources/embeddings/flair/lm-mix-german-backward-v0.2rc.pt not found in cache, downloading to C:\Users\nitra\AppData\Local\Temp\tmpl7aknp5t


100%|██████████| 72818995/72818995 [00:11<00:00, 6157732.09B/s]

2022-02-24 16:34:03,600 copying C:\Users\nitra\AppData\Local\Temp\tmpl7aknp5t to cache at C:\Users\nitra\.flair\embeddings\lm-mix-german-backward-v0.2rc.pt
2022-02-24 16:34:03,642 removing temp file C:\Users\nitra\AppData\Local\Temp\tmpl7aknp5t


In [54]:
%%time
flair_embedding_forward.embed(text)

Wall time: 5.56 s


[Sentence: "Biden befürchtet Einmarsch " in den nächsten Tagen " Stand : 18.02.2022 06:01 Uhr Die Gefahr eines russischen Einmarsches in die Ukraine schätzt US-Präsident Biden als " sehr hoch " ein - schon in den kommenden Tagen könne es dazu kommen . Die russische Regierung wies den Vize-US-Botschafter in Moskau aus . US-Präsident Joe Biden befürchtet trotz aller Beteuerungen aus Moskau einen russischen Einmarsch in die Ukraine in den kommenden Tagen . Biden sagte , die Gefahr einer Invasion sei " sehr hoch " . Nach seiner Einschätzung könne es " in den nächsten paar Tagen " dazu kommen . Es gebe keine Pläne dafür , dass er mit dem russischen Präsidenten Wladimir Putin telefonieren werde , fügte er hinzu . Der Kreml erklärte laut der russischen Agentur RIA , Bidens Warnung verstärke die Spannungen noch . Der stellvertretende Außenminister Sergej Werschinin wies vor dem UN-Sicherheitsrat die Befürchtungen des Westens vor einem bevorstehenden Einmarsch erneut zurück . " Ich denke , wir 

In [55]:
for token in text[:10]:
    print(token)
    print(token.embedding)

Token: 1 Biden
tensor([9.4392e-06, 2.0923e-02, 2.5609e-02,  ..., 3.0203e-01, 1.6694e-02,
        3.3079e-01])
Token: 2 befürchtet
tensor([ 9.1861e-06, -5.8712e-02,  3.0785e-03,  ...,  3.1815e-01,
         1.7326e-01, -1.0917e-01])
Token: 3 Einmarsch
tensor([ 8.5281e-06, -1.9479e-02,  1.4128e-02,  ..., -2.7326e-02,
         8.0130e-02,  5.8866e-01])
Token: 4 "
tensor([ 1.3426e-05, -3.8168e-02,  1.2664e-03,  ...,  4.7371e-02,
         1.8086e-01,  2.1398e-02])
Token: 5 in
tensor([ 4.8289e-06, -4.7096e-02,  1.9098e-03,  ...,  9.3630e-02,
        -1.0434e-01,  1.1621e-01])
Token: 6 den
tensor([ 4.7265e-06, -4.5689e-02,  1.7801e-04,  ...,  1.2994e-01,
         1.2650e-02, -4.0145e-02])
Token: 7 nächsten
tensor([ 2.5844e-06, -1.5880e-02,  4.4804e-05,  ...,  3.9676e-01,
         1.5711e-01,  1.9868e-02])
Token: 8 Tagen
tensor([ 5.9548e-06, -1.5614e-02,  3.6668e-03,  ...,  4.5252e-01,
         1.4140e-01,  1.4613e-01])
Token: 9 "
tensor([ 3.4456e-05, -1.4919e-02,  6.5583e-04,  ...,  4.7371e-02

## Stacked Embeddings

In [56]:
stacked_embeddings = StackedEmbeddings([
                                        embedding,
                                        flair_embedding_forward,
                                        flair_embedding_backward,
                                       ])

In [57]:
%%time
stacked_embeddings.embed(text)

Wall time: 11.1 s


In [77]:
for token in text[:10]:
    print(token)
    print(type(token.embedding))
    print(token.embedding)    
    

Token: 1 Biden
<class 'torch.Tensor'>
tensor([-0.0789,  0.2463, -0.3811,  ...,  0.3020,  0.0167,  0.3308])
Token: 2 befürchtet
<class 'torch.Tensor'>
tensor([-0.3010, -0.4519, -0.2410,  ...,  0.3182,  0.1733, -0.1092])
Token: 3 Einmarsch
<class 'torch.Tensor'>
tensor([-0.0711,  0.1360, -0.5346,  ..., -0.0273,  0.0801,  0.5887])
Token: 4 "
<class 'torch.Tensor'>
tensor([ 0.0428,  0.1169, -0.0084,  ...,  0.0474,  0.1809,  0.0214])
Token: 5 in
<class 'torch.Tensor'>
tensor([-0.1636,  0.1008, -0.0828,  ...,  0.0936, -0.1043,  0.1162])
Token: 6 den
<class 'torch.Tensor'>
tensor([-0.3198, -0.0855, -0.3333,  ...,  0.1299,  0.0126, -0.0401])
Token: 7 nächsten
<class 'torch.Tensor'>
tensor([-0.3537,  0.1262, -0.4875,  ...,  0.3968,  0.1571,  0.0199])
Token: 8 Tagen
<class 'torch.Tensor'>
tensor([-0.1788,  0.3280, -0.2208,  ...,  0.4525,  0.1414,  0.1461])
Token: 9 "
<class 'torch.Tensor'>
tensor([ 0.0428,  0.1169, -0.0084,  ...,  0.0474,  0.1809,  0.0214])
Token: 10 Stand
<class 'torch.Tensor'>

In [78]:
for token in text[:10]:
    print(token.text, token.embedding)

Biden tensor([-0.0789,  0.2463, -0.3811,  ...,  0.3020,  0.0167,  0.3308])
befürchtet tensor([-0.3010, -0.4519, -0.2410,  ...,  0.3182,  0.1733, -0.1092])
Einmarsch tensor([-0.0711,  0.1360, -0.5346,  ..., -0.0273,  0.0801,  0.5887])
" tensor([ 0.0428,  0.1169, -0.0084,  ...,  0.0474,  0.1809,  0.0214])
in tensor([-0.1636,  0.1008, -0.0828,  ...,  0.0936, -0.1043,  0.1162])
den tensor([-0.3198, -0.0855, -0.3333,  ...,  0.1299,  0.0126, -0.0401])
nächsten tensor([-0.3537,  0.1262, -0.4875,  ...,  0.3968,  0.1571,  0.0199])
Tagen tensor([-0.1788,  0.3280, -0.2208,  ...,  0.4525,  0.1414,  0.1461])
" tensor([ 0.0428,  0.1169, -0.0084,  ...,  0.0474,  0.1809,  0.0214])
Stand tensor([-0.3658,  0.1855, -0.2860,  ...,  0.1137,  0.1484,  0.3980])


In [74]:
type(token.embedding)

torch.Tensor

In [73]:
from umap import UMAP


In [75]:
# convert from torch.Tensor to numpy array

# token.embedding.cpu().detach().numpy()

In [69]:
matrix = list()
for sentence in text:
   # word_embeddings.embed(sentence)
    embedding = sentence.get_embedding().cpu().detach().numpy()
    matrix.append(embedding)

In [70]:
reducer = UMAP(n_components=2, metric='cosine', n_neighbors=15, min_dist=0.1)

In [71]:
reduced_matrix = reducer.fit_transform(matrix)

In [72]:
reduced_matrix.shape

(535, 2)